name: Build FFmpeg 4.2.2

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ffmpeg:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'
    
    - name: Setup Android NDK r21e
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip -q android-ndk-r21e-linux-x86_64.zip
        export ANDROID_NDK_HOME=$(pwd)/android-ndk-r21e
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
        echo "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential yasm pkg-config git
    
    - name: Download FFmpeg 4.2.2
      run: |
        wget https://ffmpeg.org/releases/ffmpeg-4.2.2.tar.bz2
        tar -xjf ffmpeg-4.2.2.tar.bz2
        mv ffmpeg-4.2.2 ffmpeg
    
    - name: Configure FFmpeg for armeabi-v7a
      run: |
        cd ffmpeg
        
        ARCH=arm
        CPU=armv7-a
        API=21
        
        export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
        export SYSROOT=$TOOLCHAIN/sysroot
        
        # Правильные имена компиляторов для NDK r21e
        export CC=$TOOLCHAIN/bin/armv7a-linux-androideabi${API}-clang
        export CXX=$TOOLCHAIN/bin/armv7a-linux-androideabi${API}-clang++
        export AR=$TOOLCHAIN/bin/arm-linux-androideabi-ar
        export AS=$TOOLCHAIN/bin/arm-linux-androideabi-as
        export LD=$TOOLCHAIN/bin/arm-linux-androideabi-ld
        export RANLIB=$TOOLCHAIN/bin/arm-linux-androideabi-ranlib
        export STRIP=$TOOLCHAIN/bin/arm-linux-androideabi-strip
        export NM=$TOOLCHAIN/bin/arm-linux-androideabi-nm
        
        ./configure \
          --prefix=./android-build/armeabi-v7a \
          --enable-shared \
          --disable-static \
          --disable-doc \
          --disable-programs \
          --disable-symver \
          --enable-cross-compile \
          --target-os=android \
          --arch=$ARCH \
          --cpu=$CPU \
          --cross-prefix=arm-linux-androideabi- \
          --sysroot=$SYSROOT \
          --cc=$CC \
          --cxx=$CXX \
          --enable-pic \
          --enable-avfilter \
          --enable-avcodec \
          --enable-avformat \
          --enable-avutil \
          --enable-swresample \
          --enable-swscale \
          --disable-avdevice \
          --disable-postproc \
          --enable-protocol=file \
          --enable-small
    
    - name: Build FFmpeg
      run: |
        cd ffmpeg
        export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        make -j$(nproc)
        make install
    
    - name: Package libraries and headers
      run: |
        cd ffmpeg/android-build/armeabi-v7a
        
        # Создаем структуру как в оригинальном проекте
        mkdir -p package/libs/armeabi-v7a
        mkdir -p package/include
        
        # Копируем .so файлы (все 6 библиотек)
        cp lib/libavfilter.so package/libs/armeabi-v7a/
        cp lib/libavcodec.so package/libs/armeabi-v7a/
        cp lib/libavformat.so package/libs/armeabi-v7a/
        cp lib/libavutil.so package/libs/armeabi-v7a/
        cp lib/libswresample.so package/libs/armeabi-v7a/
        cp lib/libswscale.so package/libs/armeabi-v7a/
        
        # Копируем заголовочные файлы
        cp -r include/* package/include/
        
        # Создаем архив
        cd package
        tar -czf ../ffmpeg-4.2.2-armeabi-v7a.tar.gz libs/ include/
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-armeabi-v7a
        path: ffmpeg/android-build/armeabi-v7a/ffmpeg-4.2.2-armeabi-v7a.tar.gz
    
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ffmpeg-4.2.2-${{ github.run_number }}
        name: FFmpeg 4.2.2 Build ${{ github.run_number }}
        files: ffmpeg/android-build/armeabi-v7a/ffmpeg-4.2.2-armeabi-v7a.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
